import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys {
    return {
      "en_US": {
        "language": "English",
        "payment_confirm": "your transaction is under process kindly wait for a while",
        "forget_password": "Forgot Password",
        "total_km_distance": "Total km Distance",
        "otp": "OTP",
        "new_password": "New Password",
        "confirm_new_password": "Confirm New Password",
        "submit": "Submit",
        "please_enter_otp": "Please enter OTP",
        "wrong_otp": "Wrong OTP!",
        "please_enter_password": "Please enter password",
        "password_length": "Password length must be between 6–15 characters.",
        "password_should_be_same": "Password should be same",
        "welcome_back": "Welcome Back",
        "email": "Email",
        "password": "Password",
        "forget_password?": "Forget Password?",
        "log_in": "Log In",
        "don't_have_an_account?": "Don't have an account?",
        "register": "Register",
        "enter_phone_number_to_continue": "Enter phone number to continue",
        "continue": "Continue",
        "please_enter_valid_otp": "Please enter valid otp In",
        "didn`t_get_the_otp": "Didn`t get the OTP",
        "resend_otp": "Resend OTP",
        "vehicle_details": "Vehicle Details",
        "phone": "Phone",
        "please_enter_your_mobile_number": "Please enter your mobile number.",
        "check_fare": "Check Fare",
        "Book_a_ride": "Book a ride",
        "Schedule_a_ride": "Schedule a ride",
        "sign_up": "Sign Up",
        "or_continue_with": "Or Continue with",
        "create_account": "Create\nAccount",
        "create_an_account": "Create an Account",
        "first_name": "FirstName",
        "Lastname": "LastName",
        "next": "Next",

        "service_type": "Service Type",
        "please_choose_a_service_type": "Please choose a service type",
        "confirm_password": "Confirm Password",
        "referral_code": "Referral Code",
        "referral_code_(Optional)": "Referral Code (Optional)",
        "i_have_read_and_agreed_the_terms_and_Conditions":
            "I have read and agreed the Terms and\nConditions.",
        "document": "Document",
        "data_not_found": "Data not found...",
        "edit": "Edit",
        "add": "Add",
        "add_document": "Add Document",
        "earnings": "Earnings",
        "today's_completed_target": "Today's Completed Target",
        "total_earning": "Total Earning",
        "km": "KM",
        "total_trips": "Total Trips",
        "time": "Time",
        "distance": "Distance",
        "amount": "Amount",
        "help": "Help",
        "support": "Support",
        "call": "Call",
        "message": "Message",
        "our_team_persons_will_contact_you_soon!":
            "Our team persons will contact you soon!",
        "instant_ride": "Instant request",
        "done": "Done",
        "phone_number": "Phone Number",
        "where_to": "Where To",
        "pick_from_map": "Pick From Map",
        "location_permissions_are_denied": "Location permissions are denied",
        "allow": "Allow",
        "invite_friend": "Invite Friend",
        "your_referral_code": "Your Referral Code",
        "choose_one": "choose one",
        "referral_count:": "Referral Count:",
        "referral_amount:": "Referral Amount:",
        "nio_demo": "Nio Demo",
        "from_to": "From To",
        "round_trip": "Round Trip",
        "notification_manager": "Notification Manager",
        "you_don't_have_any_notification": "You don't have any notification",
        "offers": "Offers",
        "cpd01": "CPD01",
        "10%_off_max_discount_is_50": "10% Off Max discount is 50",
        "valid_till_:_13,June_2021": "valid Till : 13,June 2021",
        "use_code": "Use Code",
        "passbook": "passbook",
        "no_wallet_history": "No Wallet History",
        "past_trip_details": "Past Trip Details",
        "pay_via": "Pay via",
        "comments": "Comments",
        "no_comments": "No Comments",
        "view_receipt": "View Receipt",
        "dispute": "Dispute",
        "you": "You",
        "driver_unprofessional": "Driver Unprofessional",
        "open": "OPEN",
        "payment": "Payment",
        "payment_options": "Payment Options",
        "by_cash": "By Cash",
        "profile": "Profile",
        "service": "Service",
        "looking_to_change_password": "Looking to change password",
        "save": "Save",
        "setting": "Setting",
        "choose_language": "Choose Language",
        "summary": "Summary",
        "total_no_of_rides": "Total No. Of Rides",
        "revenue": "Revenue",
        "no._of_scheduled_rides": "No.Of Scheduled Rides",
        "cancelled_ride": "Cancelled Ride",
        "wallet": "Wallet",
        "your_wallet_amount": "Your Wallet Amount",
        "transaction_id": "Transaction Id",
        "date": "Date",
        "your_trips": "Your Trips",
        "add_toll_charge": "Add Toll Charge",
        "add_Toll": "Add Toll",
        "dismiss": "Dismiss",
        "please_enter_valid_amount": "Please enter valid amount",
        "please_confirm_the_address": "",
        "picked_up_location": "Picked up Location",
        "drop_location": "Drop Location",
        "confirm": "Confirm",
        "otp_verification": "OTP Verification",
        "cancel": "Cancel",
        "reason_for_canceling": "Reason or canceling",
        "something_went_wrong": "Something went wrong...",
        "scan_the_qr_to_fetch_mobile_number":
            "Scan the QR to fetch mobile number",
        "otp_verified": "OTP Verified!",
        "invoice": "Invoice",
        "booking_id": "Booking ID",
        "time_taken": "Time Taken",
        "base_fare": "Base Fare",
        "time_fare": "Time Fare",
        "tax": "Tax",
        "toll_charges": "Toll Charges",
        "round_off": "Round off",
        "total": "Total",
        "payable": "Payable",
        "close": "Close",
        "time_remaining": "Time Remaining",
        "pick_up_location": "Pick Up Location",
        "decline": "Decline",
        "accept": "Accept",
        "confirm_payment": "Confirm Payment",
        "no_data_found": "No data found..",
        "ratings_your_trip_with": "Rate the customer",
        "write_your_comment": "Write your comment",
        "are_you_sure_want_to_cancel_this_request":
            "Are you sure want to Cancel this request?",
        "arrived": "Arrived",
        "picked_up": "Picked Up",
        "arrived_location": "Arrived Location",
        "waiting_time": "Waiting Time",
        "tap_when_dropped": "TAP WHEN DROPPED",
        "hey_checkout_this_app": "Hey Checkout this app,Mozlit Driver",
        "are_you_sure_want_to_logout": "Are you sure want to logout?",
        "no": "NO",
        "yes": "Yes",
        "add_card_for_payments": "Add card for payments",
        "card_number": "Card Number",
        "mozilit_driver": "Mozilit Driver",
        "expiration_date": "Expiration Date",
        "cvv": "CVV",
        "add_card": "Add Card",
        "please_insert_valid_expiry_date": "Please insert valid expiry date",
        "change_password": "Change\nPassword",
        "current_password": "Current Password",
        "terms_Condition": "Terms & Condition Password",
        "chat": "Chat",
        "loading": "Loading...",
        "type_something_here": "Type Something Here",
        "swipe_to_online": "Swipe to online",
        "swipe_to_offline": "Swipe to offline",
        "could_not_launch": "Could not launch",
        "qr_scan": "Qr Scan",
        "your_tips": "Your Tips",
        "earning": "Earning",
        "card": "Card",
        "share": "Share",
        "logout": "Logout",
        "ride_updated": "Ride Updated",
        "hi": "Hi, ",
        "past_rides": "Past requests",
        "account": "Account",
        "source": "Source",
        "destination": "Destination",
        "user_arrogant_and_rude": "User arrogant and rude",
        "charging_stations": "Charging Stations",
        "give_feedback": "Give Feedback",
        "terms_and_conditions": "Terms And Conditions",
        "privacy_policy": "Privacy Policy",
        "our_you_soon!": "Our team person will contact you soon!",
        "add_money": "Add Money",
        "add_amount": "Add Amount",
        "together": "Together, we\'re growing\nStronger and further",
        "refer_now_and_earn": "Refer Now and Earn",
        "or": "Or",
        "share_your_link_via": "Share your link via",
        "spread_the_word": "Spread the word, And we will\nreward you",
        "get INR 100 in your Eto wallet for every friend you refer":
            "Get INR 100 in your Arby wallet for every friend you refer",
        "refCode:": "Referral Code:",
        "delete_account": "Delete\nAccount",
        "trip_details": "Trip Details",
        "start_ride": "Start Ride",
        "end_ride": "End Ride",
        "leave_a_feedback": "Leave a Feedback",
        "Please_type_the_verification_code_sent_to_your":
            "Please type the verification code sent to your",
        "mobile_number": " Mobile Number",
        "your_email": " Email",
        "verification_code": "Verification Code",
        "forgot_password": "Forgot Password",
        "Driver_Registration": "Driver Registration",
        "Vehicle_Registration": "Vehicle Registration",
        "did_get_the_OTP": "didn`t Get The OTP?",
        "look_for_new_ride": "Look For New Trip",
        "car_type": "Truck type",
        "car_name": "Truck name",
        "car_color": "Truck color",
        "car_model": "Truck model",
        "car_number": "Truck number",
        "please_enter_amount": "Please enter amount",
        "Please_enter_more_when_amount": "Please_enter_more_when_amount",
        "sorry_for_inconvenience_time_Our_partner": "Sorry for inconvience time, Our partner or busy. Please try after some time",
        "We_are_searching_for_new_driver_please_wait_till_we_get_the_new_driver": "We are searching for new driver, please wait till we get the new driver.",

     "have_a_nice_day":"Have a nice day"
      },
      "hi_IN": {
        "vehicle_details": "वाहन की सूचना",
        "car_model": "ट्रक मॉडल",
        "sorry_for_inconvenience_time_Our_partner": "असुविधा के समय के लिए खेद है, हमारे साथी या व्यस्त। कृपया कुछ देर बाद प्रयास करें",
        "car_color": "ट्रक का रंग",
        "please_enter_amount": "कृपया राशि दर्ज करें",
        "Please_enter_more_when_amount": "कृपया अधिक कब दर्ज करें",
        "We_are_searching_for_new_driver_please_wait_till_we_get_the_new_driver": "हम नए ड्राइवर की तलाश कर रहे हैं, कृपया तब तक प्रतीक्षा करें जब तक हमें नया ड्राइवर नहीं मिल जाता।",
        "look_for_new_ride": "नई सवारी की तलाश करें",
        "payment_confirm": "आपका लेनदेन प्रक्रियाधीन है कृपया थोड़ी देर प्रतीक्षा करें",
        "Driver_Registration": "चालक पंजीकरण",
        "Vehicle_Registration": "वाहन पंजीकरण",
        "next": "अगला",
        "language": "हिन्दी",
        "forgot_password": " पासवर्ड भूल गए ",
        "total_km_distance": "कुल किमी दूरी",
        "otp": " ओटीपी ",
        "new_password": " नया पासवर्ड ",
        "confirm_new_password": " नए पासवर्ड की पुष्टि करें ",
        "submit": " प्रस्तुत करना ",
        "please_enter_otp": " कृपया ओटीपी दर्ज करें ",
        "wrong_otp": " गलत ओटीपी ",
        "please_enter_password": " कृप्या पास्वर्ड भरो ",
        "password_length": " पासवर्ड की लंबाई 6-15 अक्षरों के बीच होनी चाहिए.",
        "password_should_be_same": " पासवर्ड समान होना चाहिए ",
        "welcome_back": " वापसी पर स्वागत है ",
        "email": " ईमेल ",
        "password": " पासवर्ड ",
        "log_in": " लॉग इन करें ",
        "don't_have_an_account?": " खाता नहीं है?",
        "register": " पंजीकरण करवाना ",
        "verification_code": " पुष्टि संख्या ",
        "continue": " जारी रखना ",
        "please_enter_valid_otp": " कृपया मान्य ओटीपी दर्ज करें ",
        "didn`t_get_the_OTP": " ओटीपी नहीं मिला ",
        "resend_OTP": " ओटीपी पुनः भेजें ",
        "enter_phone": " जारी रखने के लिए फ़ोन नंबर दर्ज करें ",
        "phone": " फ़ोन ",
        "please_number.": " अपना मोबाइल नंबर दर्ज करें.",
        "check_fare": " किराया जांचें ",
        "Book_a_ride": "सवारी बुक करें",
        "Schedule_a_ride": "एक राइड शेड्यूल करें",
        "sign_up": " साइन अप करें ",
        "Or_continue_with": " या साथ जारी रखें ",
        "create_account": " खाता बनाएं ",
        "create_an_account": " खाता बनाएं ",
        "first_name": " पहला नाम ",
        "last_name": " उपनाम ",
        //"car_model": " कार के मॉडल ",
        "car_number": " ट्रक का नबंर ",
        "did_get_the_OTP": "नहीं मिला ओटॉप? ",
        "service_type": " सेवा प्रकार ",
        "please_choose_a_service_type": " कृपया एक सेवा प्रकार चुनें ",
        "confirm_password": " पासवर्ड की पुष्टि कीजिये ",
        "referral_code": " रेफरल कोड ",
        "referral_code_(Optional)": " रेफरल कोड (वैकल्पिक)",
        "i_have_read_and_agreed_the_terms_and_Conditions":
            " मैंने नियम और शर्तें पढ़ ली हैं और उनसे सहमत हूं.",
        "document": "दस्तावेज़",
        "data_not_found": " डेटा नहीं मिला...",
        "edit": " संपादन करना ",
        "add": " जोड़ें ",
        "add_document": " दस्तावेज़ जोड़ें ",
        "earnings": "आय",
        "today's_completed_target": " आज का लक्ष्य पूरा ",
        "total_earning": " कुल कमाई ",
        "km": "KM",
        "total_trips": " कुल यात्राएं ",
        "time": " समय ",
        "distance": " दूरी ",
        "amount": " राशि ",
        "help": "मदद",
        "support": " सहायता ",
        "call": " बुलाना ",
        "message": " संदेश ",
        "our_team_persons_will_contact_you_soon!":
            " हमारी टीम के लोग जल्द ही आपसे संपर्क करेंगे!",
        "instant_ride": "तत्काल अनुरोध",
        "done": " पूर्ण ",
        "phone_number": " फ़ोन नंबर ",
        "where_to": " जहां ",
        "pick_from_map": " मानचित्र से चुनें ",
        "location_permissions_are_denied": " स्थान अनुमतियां अस्वीकृत हैं ",
        "allow": " अनुमति देना ",
        "invite_friend": "मित्र को न्योता ",
        "your_referral_code": "आपका रेफरल कोड ",
        "choose_one": " एक का चयन ",
        "referral_count:": "रेफरल काउंट:",
        "referral_amount:": " रेफरल राशि:",
        "nio_demo": " निओ डेमो ",
        "from_to": " से ",
        "round_trip": " राउंड ट्रिप ",
        "notification_manager": " अधिसूचना प्रबंधक ",
        "you_don't_have_any_notification": " आपके पास कोई सूचना नहीं है ",
        "offers": " ऑफर ",
        "cpd01": "CPD01",
        "10%_off_max_discount_is_50": "अधिकतम छूट पर 10% की छूट 50 है",
        "valid_till_:_13,June_2021": " तक वैध: 13, जून 2021",
        "use_code": " कोड का प्रयोग करें ",
        "passbook": "पासवृकk",
        "no_wallet_history": " कोई बटुआ इतिहास नहीं ",
        "past_trip_details": " पिछली यात्रा का विवरण ",
        "pay_via": " माध्यम से भुगतान करें ",
        "comments": " टिप्पणियाँ ",
        "no_comments": " कोई टिप्पणी नहीं ",
        "view_receipt": " रसीद देखें ",
        "dispute": " विवाद ",
        "you": " आप ",
        "driver_unprofessional": " चालक अव्यवसायिक ",
        "open": " खोलना ",
        "payment": " भुगतान ",
        "payment_options": " भुगतान विकल्प ",
        "by_cash": " नकद द्वारा ",
        "profile": " प्रोफ़ाइल ",
        "service": " सेवा ",
        "looking_to_change_password": " पासवर्ड बदलना चाह रहे हैं ",
        "save": " बचाना ",
        "setting": " स्थापना ",
        "choose_language": "भाषा चुनें",
        "summary": " सारांश ",
        "total_no_of_rides": " सवारी की कुल संख्या ",
        "revenue": " आय ",
        "no._of_scheduled_rides": " अनुसूचित सवारी की संख्या ",
        "cancelled_ride": " रद्द की गई सवारी ",
        "wallet": "बटुआ",
        "your_wallet_amount": " आपकी वॉलेट राशि ",
        "transaction_id": "लेनदेन आईडी ",
        "date": " दिनांक ",
        "your_trips": " आपकी यात्राएं ",
        "add_toll_charge": " टोल चार्ज जोड़ें ",
        "add_Toll": " टोल जोड़ें ",
        "dismiss": " नकार देना ",
        "please_enter_valid_amount": " कृपया मान्य राशि दर्ज करें ",
        "please_confirm_the_address": " कृपया पते की पुष्टि करें ",
        "picked_up_location": " उठाया स्थान ",
        "drop_location": " ड्रॉप स्थान ",
        "confirm": " पुष्टि करें ",
        "otp_verification": " ओटीपी सत्यापन ",
        "cancel": " रद्द करना ",
        "reason_for_canceling": " कारण या रद्द करना ",
        "something_went_wrong": " कुछ गलत हो गया...",
        "scan_the_qr_to_fetch_mobile_number":
            " मोबाइल नंबर प्राप्त करने के लिए क्यूआर स्कैन करें ",
        "otp_verified": " ओटीपी सत्यापित!",
        "invoice": " इनवॉइस ",
        "booking_id": " बुकिंग आईडी ",
        "time_taken": " समय लिया ",
        "base_fare": " बुनियादी भाड़ा ",
        "time_fare": " समय किराया ",
        "tax": " कर ",
        "toll_charges": " टोल शुल्क ",
        "round_off": " पूर्णांक करना ",
        "total": " कुल ",
        "payable": " देय ",
        "close": " बंद करना ",
        "time_remaining": " शेष समय ",
        "pick_up_location": " उठाने की जगह ",
        "decline": " पतन ",
        "accept": " स्वीकार करना ",
        "confirm_payment": " भुगतान की पुष्टि करें ",
        "no_data_found": " कोई डेटा नहीं मिला..",
        "ratings_your_trip_with": " ग्राहक को रेट करें ",
        "write_your_comment": " अपनी टिप्पणी लिखें ",
        "are_you_sure_want_to_cancel_this_request":
            " क्या आप वाकई इस अनुरोध को रद्द करना चाहते हैं?",
        "arrived": " पहुंच गए ",
        "picked_up": " उठाया ",
        "arrived_location": " पहुंचने का स्थान ",
        "waiting_time": " इंतजार का समय ",
        "tap_when_dropped": " पहुंचने पर टैप करें ",
        "hey_checkout_this_app": " अरे इस ऐप को चेकआउट करें ",
        "are_you_sure_want_to_logout": " क्या आप वाकई लॉग आउट करना चाहते हैं?",
        "no": " ना ",
        "yes": " हाँ ",
        "add_card_for_payments": " भुगतान के लिए कार्ड जोड़ें ",
        "card_number": " कार्ड नंबर ",
        "mozilit_driver": " ईटीओ चालक ",
        "expiration_date": " समाप्ति तिथि ",
        "cvv": "CVV",
        "add_card": " कार्ड जोड़ें ",
        "please_insert_valid_expiry_date": " कृपया मान्य समाप्ति तिथि डालें ",
        "change_password": " पासवर्ड\nबदलें ",
        "current_password": " वर्तमान पासवर्ड ",
        "terms_Condition": " नियम और शर्त पासवर्ड ",
        "terms_and_Condition": " नियम व शर्त ",
        "chat": " बात करना ",
        "loading": " लोड हो रहा है...",
        "type_something_here": " यहाँ कुछ टाइप करें ",
        "swipe_to_online": " ऑनलाइन जाने के लिए स्वाइप करें ",
        "swipe_to_offline": " ऑफ़लाइन जाने के लिए स्वाइप करें ",
        "could_not_launch": "लॉन्च नहीं कर सका ",
        "qr_scan": "क्यूआर स्कैन ",
        "your_tips": "आपकी युक्तियाँ ",
        "earning": "कमाई ",
        "card": "कार्ड ",
        "share": " ेयर करना ",
        "logout": "लॉग आउट",
        "hi": "नमस्ते",
        "past_rides": "पिछले अनुरोध",
        "account": "खाता",
        "source": "स्रोत",
        "destination": "गंतव्य",
        "user_arrogant_and_rude": "उपयोगकर्ता अभिमानी और असभ्य",
        "charging_stations": "चार्जिंग स्टेशन",
        "give_feedback": "प्रतिक्रिया दें",
        "terms_and_conditions": "नियम और शर्तें",
        "privacy_policy": "गोपनीयता नीति",
        "our_you_soon!": "हमारी टीम के सदस्य जल्द ही आपसे संपर्क करेंगे!",
        "add_money": "पैसे जोड़ें",
        "add_amount": "राशि जोड़ें",
        "together": "साथ में, हम\nमजबूत और आगे बढ़ रहे हैं",
        "refer_now_and_earn": "अभी देखें और कमाएं",
        "or": "या",
        "share_your_link_via": "के माध्यम से अपना लिंक साझा करें",
        "spread_the_word": "प्रचार करें, और हम आपको\nपुरस्कृत करेंगे",
        "get INR 100 in your Eto wallet for every friend you refer":
            "आपके द्वारा संदर्भित प्रत्येक मित्र के लिए अपने Arby वॉलेट में INR 100 प्राप्त करें",
        "refCode:": "रेफरल कोड:",
        "car_type": "ट्रक प्रकार",
        "car_name": "ट्रक का नाम",
        "delete_account": "खाता\nहटा दो",
        "trip_details": "यात्रा विवरण",
        "start_ride": "राइड शुरू करें",
        "end_ride": "सवारी समाप्त करें",
        "feedback_for_the_user": "उपयोगकर्ता के लिए प्रतिक्रिया",
        "Please_type_the_verification_code_sent_to_your":
            "कृपया आपके पर भेजा गया सत्यापन कोड टाइप करें",
        "mobile_number": "मोबाइल नंबर",
        "your_email": " ईमेल"
      },
      "nl_NL": {
        "language": "Dutch",
        "car_name": "vrachtwagen naam",
        "car_type": "vrachtwagen type",
        "forgot_password": "Wachtwoord vergeten",
        "car_color": "Vrachtwagen kleur",
        "past_rides": "Eerdere verzoeken",
        "otp": "OTP",
        "new_password": "nieuw paswoord",
        "confirm_new_password": "Bevestig nieuw wachtwoord",
        "submit": "Indienen",
        "please_enter_otp": "Voer alstublieft OTP in",
        "wrong_otp": "Verkeerde OTP!",
        "please_enter_password": "Voer wachtwoord in alstublieft",
        "password_length":
            "De lengte van het wachtwoord moet tussen 6-15 tekens zijn.",
        "password_should_be_same": "Wachtwoord moet hetzelfde zijn",
        "welcome_back": "Welkom\nterug",
        "email": "E-mail",
        "password": "Wachtwoord",
        "forget_password": "Wachtwoord vergeten?",
        "log_in": "Log In",
        "don't_have_an_account?": "Don't have an account?",
        "register": "Register",
        "enter_phone_number_to_continue":
            "Voer telefoonnummer in om door te gaan",
        "please_type_the_verification_code_sent_to_your":
            "Typ de verificatiecode a.u.b.\nverzonden naar uw",
        "continue": "Doorgaan",
        "please_enter_valid_otp": "Voer een geldige otp In . in",
        "didn`t_get_the_otp": "Ik heb de OTP niet gekregen",
        "resend_otp": "OTP OPNIEUW VERZENDEN",
        "phone": "Telefoon",
        "please_enter_your_mobile_number":
            "Voer alstublieft uw mobiele nummer in.",
        "check_are": "Controleer tarief",
        "sign_up": "Aanmelden",
        "or_continue_with": "Of Ga verder met",
        "create_account": "Creëren\nAccount",
        "firstname": "Voornaam",
        "Lastname": "Achternaam",
        "car_model": "vrachtwagenmodel",
        "car_number": "truck nummer",
        "service_type": "Dienst Type",
        "please_choose_a_service_type": "Kies een servicetype",
        "confirm_password": "bevestig wachtwoord",
        "referral_code": "Verwijzingscode:",
        "referral_code_(Optional)": "Verwijzingscode (optioneel)",
        "i_have_read_and_agreed_the_terms_and_Conditions":
            "Ik heb de voorwaarden gelezen en ga ermee akkoord en\nConditie.",
        "document": "Document",
        "data_not_found": "Data niet gevonden...",
        "edit": "Bewerk",
        "add_document": "Document toevoegen",
        "earnings": "Inkomsten",
        "today's_completed_target": "Het voltooide doel van vandaag",
        "total_earning": "Totale winst",
        "km": "KM",
        "total_trips": "Totaal aantal reizen",
        "time": "Tijd",
        "distance": "Afstand",
        "amount": "Hoeveelheid",
        "help": "Helpen",
        "support": "Steun",
        "call": "Telefoongesprek",
        "message": "Bericht",
        "our_team_persons_will_contact_you_soon!":
            "Onze teamleden nemen spoedig contact met u op!",
        "instant_ride": "direct verzoek",
        "done": "Gedaan",
        "phone_number": "Telefoonnummer",
        "where_to": "Waarheen",
        "pick_from_map": "Kies uit kaart",
        "location_permissions_are_denied": "Locatierechten zijn geweigerd",
        "allow": "Toestaan",
        "invite_friend": "Nodig een vriend uit",
        "your_referral_code": "Uw verwijzingscode",
        "choose_one": "kies er een",
        "referral_count_:": "Aantal verwijzingen:",
        "referral_amount:": "Verwijzingsbedrag:",
        "nio_demo": "Nio-demo",
        "from_to": "Van naar",
        "round_trip": "Rondvaart",
        "notification_manager": "Meldingsmanager",
        "you_don't_have_any_notification": "Je hebt geen melding",
        "offers": "Aanbiedingen",
        "cpd01": "CPD01",
        "10%_off_max_discount_is_50": "10% korting Max korting is 50",
        "valid_till_:_13,June_2021": "geldig t/m : 13 juni 2021",
        "use_code": "Gebruik code",
        "passbook": "bankboekje",
        "no_wallet_history": "Geen portemonnee-geschiedenis",
        "past_trip_details": "Eerdere reisdetails",
        "pay_via": "Betalen via",
        "comments": "Opmerkingen",
        "no_comments": "Geen reacties",
        "view_receipt": "Bekijk bon",
        "dispute": "Onenigheid",
        "you": "Jij",
        "driver_unprofessional": "Bestuurder onprofessioneel",
        "open": "OPEN",
        "payment": "Betaling",
        "payment_options": "Betalingsmogelijkheden",
        "by_cash": "Contant",
        "profile": "Profiel",
        "service": "Onderhoud",
        "looking_to_change_password": "Op zoek naar wachtwoord wijzigen",
        "save": "Opslaan",
        "setting": "instelling",
        "choose_language": "Kies een taal",
        "summary": "Zomers",
        "total_no_of_rides": "Totaal aantal rijders",
        "revenue": "Omzet",
        "no._of_scheduled_rides": "Aantal geplande ritten",
        "cancelled_ride": "Geannuleerde rit",
        "wallet": "Portemonnee",
        "your_wallet_amount": "Uw Wallet-bedrag",
        "transaction_id": "Transactie ID",
        "date": "Datum",
        "your_trips": "Uw reizen",
        "add_tall_charge": "Hoge kosten toevoegen",
        "add_Toll": "Tol toevoegen",
        "dismiss": "Afwijzen",
        "please_enter_valid_amount": "Voer een geldig bedrag in",
        "please_confirm_the_address": "Bevestig het adres a.u.b",
        "picked_up_location": "Opgehaalde locatie",
        "drop_location": "Plaats neerzetten",
        "confirm": "Bevestigen",
        "otp_verification": "OTP-verificatie",
        "cancel": "Annuleren",
        "reason_for_canceling": "Reden of opzegging",
        "something_went_wrong": "Er is iets fout gegaan...",
        "scan_the_qr_to_fetch_mobile_number":
            "Scan de QR om het mobiele nummer op te halen",
        "otp_verified": "OTP geverifieerd!",
        "invoice": "Factuur",
        "booking_id": "Boekings-ID",
        "time_taken": "Tijd genomen",
        "base_fare": "Basistarief",
        "time_fare": "Tijdtarief",
        "tax": "Belasting",
        "toll_charges": "Tolkosten",
        "round_off": "Afronden",
        "total": "Totaal",
        "payable": "te betalen",
        "close": "Dichtbij",
        "time_remaining": "Time Remaining",
        "pick_up_location": "Ophaalplaats",
        "decline": "Afwijzen",
        "accept": "Aanvaarden",
        "confirm_payment": "Bevestig betaling",
        "no_data_found": "Geen data gevonden..",
        "ratings_your_trip_with": "Beoordeel de klant",
        "write_your_comment": "Schrijf je commentaar",
        "are_you_sure_want_to_cancel_this_request":
            "Weet u zeker dat u dit verzoek wilt annuleren?",
        "arrived": "aangekomen",
        "picked_up": "Opgepikt",
        "arrived_location": "Aangekomen locatie",
        "waiting_time": "Wachttijd",
        "tap_when_dropped": "TIK WANNEER UITGEVALLEN",
        "hey_checkout_this_app": "Hey Check deze app, Mozlit Driver",
        "are_you_sure_want_to_logout": "Weet u zeker dat u wilt uitloggen?",
        "no": "Nee",
        "yes": "Ja",
        "add_card_for_payments": "Kaart toevoegen voor betalingen",
        "card_number": "Kaartnummer",
        "mozilit_driver": "Mozilit-stuurprogramma",
        "expiration_date": "vervaldatum",
        "cvv": "CVV",
        "add_card": "Voeg een kaart toe",
        "please_insert_valid_expiry_date": "Voer een geldige vervaldatum in",
        "change_password": "Change Password",
        "current_password": "huidig \u200B\u200Bwachtwoord",
        "terms_Condition": "Algemene voorwaarden Wachtwoord",
        "chat": "Chatten",
        "loading": "Bezig met laden...",
        "type_something_here": "Typ hier iets",
        "swipe_to_online": "Veeg naar online",
        "swipe_to_offline": "Veeg naar offline",
        "could_not_launch": "Kan niet starten",
        "qr_scan": "Qr-scan",
        "your_tips": "Uw tips",
        "earning": "Verdienen",
        "card": "Kaart",
        "share": "Deel",
        "logout": "Uitloggen",
        "ride_updated": "Rit bijgewerkt"
      }
    };
  }
}
